# Generated by Django 5.1.3 on 2024-12-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_slug_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_to_read',
            field=models.CharField(max_length=15, null=True, verbose_name='time to read'),
        ),
    ]
