# Generated by Django 5.1.3 on 2024-12-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_time_to_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_to_read',
            field=models.CharField(max_length=15, verbose_name='time to read'),
        ),
    ]
